version: "3.3"
services:
  db:
    image: postgres:12.2-alpine
    env_file:
      - .env
    restart: always
    volumes:
      - ${POSTGRES_DATA_FOLDER}:/var/lib/postgresql/data
    expose:
      - 5432
  # Uncomment this if you wish to use adminer
  # adminer:
  #     image: adminer
  #     restart: always
  #     depends_on:
  #         - db
  #     ports:
  #       - ${ADMINER_PORT}:8080
  uchu:
    build:
      context: .
      dockerfile: Uchu.Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ${GAME_FOLDER}:/res
    ports:
      - ${UCHU_HANDSHAKE_PORT}:1001
      - ${UCHU_CHARACTER_PORT}:2002
      - ${UCHU_CHAT_PORT}:2004
      - ${UCHU_API_PORT_RANGE}:10000-10100
      - ${UCHU_WORLD_PORT_RANGE}:20000-20100
      - ${UCHU_SERVER_PORT}:21836
      - ${UCHU_AUTH_PORT}:40000
      - ${UCHU_HANDSHAKE_PORT}:1001/udp
      - ${UCHU_CHARACTER_PORT}:2002/udp
      - ${UCHU_CHAT_PORT}:2004/udp
      - ${UCHU_API_PORT_RANGE}:10000-10100/udp
      - ${UCHU_WORLD_PORT_RANGE}:20000-20100/udp
      - ${UCHU_SERVER_PORT}:21836/udp
      - ${UCHU_AUTH_PORT}:40000/udp
    tty: true
    stdin_open: true
