version: "3.8"
services:
  db:
    image: postgres:12.2-alpine
    env_file:
      - .env
    restart: always
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - ${DATA_FOLDER}:/var/lib/postgresql/data
  adminer:
      image: adminer
      restart: always
      depends_on:
          - db
      ports:
        - "${ADMINER_PORT}:8080"
  redis:
    image: redis:6.0.8-alpine
    env_file:
      - .env
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ${DATA_FOLDER}:/data
  uchu:
    build:
      context: .
      dockerfile: Uchu.Dockerfile
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - ${GAME_FOLDER}:/res
    ports:
      - "2002:${CHARACTER_PORT}"
      - "10000-10100:${API_PORT}-${MAX_API_PORT}"
    tty: true
    stdin_open: true
